# Generated by Django 4.2.1 on 2023-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_variation_variation_category'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.variation'),
        ),
    ]
