# Generated by Django 4.2.1 on 2023-08-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
