# Generated by Django 4.2.1 on 2023-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='newly_added',
            field=models.BooleanField(default=False),
        ),
    ]
