# Generated by Django 4.2.1 on 2023-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Now', max_length=100),
        ),
    ]
