# Generated by Django 4.2.1 on 2023-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0007_order_order_product_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('New', 'New'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='New', max_length=100),
        ),
    ]
