# Generated by Django 4.2.1 on 2023-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Completed', 'Completed'), ('New', 'New'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default=None, max_length=100),
        ),
    ]
