# Generated by Django 4.2.1 on 2023-08-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Placed', 'Placed'), ('New', 'New'), ('Delivered', 'Delivered')], default='New', max_length=100),
        ),
    ]
