# Generated by Django 4.2.1 on 2023-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0034_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('New', 'New'), ('Delivered', 'Delivered')], default='New', max_length=100),
        ),
    ]
