# Generated by Django 4.2.1 on 2023-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0042_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('New', 'New'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='New', max_length=100),
        ),
    ]
