# Generated by Django 4.2.1 on 2023-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderss', '0049_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('New', 'New'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=100),
        ),
    ]
