# Generated by Django 4.2.1 on 2023-08-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variation_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
