# Generated by Django 4.2.1 on 2023-09-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_productgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
    ]
